name: Build OpenWrt(v22.03.5) for x86_64

on:
  repository_dispatch:
  workflow_dispatch:

env:
  OPENWRT_BRANCH: v22.03.5
  CONFIG: config/v22.03.5-x86_64
  OPENWRT_ROOT_PATH: openwrt
  THREADS: $(nproc)
  CLEAN_DL: '1'
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialize Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq -y upgrade
        sudo -E apt-get -y install $(cat $GITHUB_WORKSPACE/openwrt-env)
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        
    - name: Checkout digidrifter
      uses: actions/checkout@v3
      
    - name: Checkout OpenWrt
      uses: actions/checkout@v3
      with:
        repository: openwrt/openwrt
        path: ${{env.OPENWRT_ROOT_PATH}}
        ref: ${{env.OPENWRT_BRANCH}}
        
    - name: Update feeds
      run: |
        cd ${{env.OPENWRT_ROOT_PATH}}
        ./scripts/feeds clean
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        [ -e ${{env.CONFIG}} ] && cp ${{env.CONFIG}} ${{env.OPENWRT_ROOT_PATH}}/.config || echo "! CONFIG file ${{env.CONFIG}} does not exist"
        cd ${{env.OPENWRT_ROOT_PATH}}
        make defconfig
        cat .config
        
    - name: Generate Variables
      id: env
      run: |
        cd ${{env.OPENWRT_ROOT_PATH}}
        export DEVICE_TARGET=$(cat .config | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
        echo DEVICE_TARGET is $DEVICE_TARGET
        
        export DEVICE_SUBTARGET=$(cat .config | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
        echo DEVICE_SUBTARGET is $DEVICE_SUBTARGET

    - name: Make Download
      run: |
        cd ${{env.OPENWRT_ROOT_PATH}}
        make download -j${{env.THREADS}}
        df -hT

    - name: Compile
      run: |
        cd ${{env.OPENWRT_ROOT_PATH}}
        make -j${{env.THREADS}} || make -j1 V=s
        
    - name: Print Sha256sums
      run: |
        cd ${{env.OPENWRT_ROOT_PATH}}/bin/targets/$DEVICE_TARGET/$DEVICE_SUBTARGET
        cat sha256sums
    
    - name: Show bin
      run: |
        cd ${{env.OPENWRT_ROOT_PATH}}/bin
        ls -lA
        
    - name: Show targets
      run: |
        cd ${{env.OPENWRT_ROOT_PATH}}/bin/targets
        echo ========================= $(pwd) =========================
        ls -lR

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-${{env.OPENWRT_VERSION}}-${{env.DEVICE_TARGET}}_${{env.DEVICE_SUBTARGET}}
        path: ${{env.OPENWRT_ROOT_PATH}}/bin/targets/${{env.DEVICE_TARGET}}/${{env.DEVICE_SUBTARGET}}/*

