name: Build OpenWrt v22.03.5 for x86_64

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  OPENWRT_BRANCH: v22.03.5
  CONFIG: config/v22.03.5-x86_64
  THREADS: $(nproc)
  CLEAN_DL: '1'

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout digidrifter
      uses: actions/checkout@v3
      
    - name: Checkout OpenWrt
      uses: actions/checkout@v3
      with:
        repository: openwrt/openwrt
        path: openwrt
        ref: ${{env.OPENWRT_BRANCH}}

    - name: Show env
      run: |
        echo 1 CONFIG is ${{env.CONFIG}}
        echo 2 CONFIG is ${CONFIG}
        echo 3 CONFIG is $CONFIG
        echo 4 CONFIG is "$CONFIG"
    
    - name: Apply config
      run: |
        
        echo ------------ $(pwd) -------------
        ls -la
        echo ------------ config -------------
        ls -l config
        echo ------------ config/v22.03.5-x86_64 -------------
        ls -l config/v22.03.5-x86_64
        [ -e "$CONFIG" ] && cp "$CONFIG" openwrt/.config || echo "! CONFIG file $CONFIG does not exist"
        cd openwrt
        ls -l .config
        cat .config
        
    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Apply config
      run: |
        ls -l config
        ls -l config/v22.03.5-x86_64
        [ -e ${{env.CONFIG}} ] && cp ${{env.CONFIG}} openwrt/.config || echo "! CONFIG file ${{env.CONFIG}} does not exist"
        cd openwrt
        ls -l .config
        cat .config

    - name: Make Download
      run: |
        cd openwrt
        make defconfig
        cat .config
        make download -j${{env.THREADS}}

    - name: Compile
      run: |
        cd openwrt
        make -j${{env.THREADS}} || make -j1 V=s
    
    - name: Show bin
      run: |
        cd openwrt/bin
        ls -lA
        
    - name: Show targets
      run: |
        cd openwrt/bin/targets
        ls -lR

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-$OPENWRT_VERSION-x86_64
        path: openwrt/bin/targets/x86_64/*

