name: Build OpenWrt(v22.03.5) for x86_64

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  OPENWRT_BRANCH: v22.03.5
  CONFIG: config/v22.03.5-x86_64
  THREADS: $(nproc)
  CLEAN_DL: '1'

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout digidrifter
      uses: actions/checkout@v3
      
    - name: Checkout OpenWrt
      uses: actions/checkout@v3
      with:
        repository: openwrt/openwrt
        path: openwrt
        ref: ${{env.OPENWRT_BRANCH}}

    - name: Show env
      run: |
        echo 1 CONFIG is ${{env.CONFIG}}
        echo 2 CONFIG is ${CONFIG}
        echo 3 CONFIG is $CONFIG
        echo 4 CONFIG is "$CONFIG"
        
    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds clean
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        [ -e ${{env.CONFIG}} ] && cp ${{env.CONFIG}} openwrt/.config || echo "! CONFIG file ${{env.CONFIG}} does not exist"
        cd openwrt
        make defconfig
        cat .config
        
    - name: Generate Variables
      id: env
      run: |
        cd openwrt
        export DEVICE_TARGET=$(cat .config | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
        echo DEVICE_TARGET is $DEVICE_TARGET
        
        export DEVICE_SUBTARGET=$(cat .config | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
        echo DEVICE_SUBTARGET is $DEVICE_SUBTARGET

    - name: Make Download
      run: |
        make download -j${{env.THREADS}}
        df -hT

    - name: Compile
      run: |
        cd openwrt
        make -j${{env.THREADS}} || make -j1 V=s
        
    - name: Print Sha256sums
      run: |
        cd openwrt/bin/targets/$DEVICE_TARGET/$DEVICE_SUBTARGET
        cat sha256sums
    
    - name: Show bin
      run: |
        cd openwrt/bin
        ls -lA
        
    - name: Show targets
      run: |
        cd openwrt/bin/targets
        echo ========================= $(pwd) =========================
        ls -lR

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-${{env.OPENWRT_VERSION}}-x86_64
        path: openwrt/bin/targets/x86/64/*

