name: Compile OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  REPO_BRANCH: openwrt-22.03

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@main

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext unzip file libssl-dev wget

    - name: Clone source code
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Prepare environment
      run: |
        cd openwrt
        make defconfig

    - name: Select target and packages
      run: |
        cd openwrt
        # 搜索以#开头，带有x86的字符串，并删除字符串开头的#号
        sed -i 's/^#\(.*x86.*\)$/\1/' .config
        cat .config
        make defconfig
        
    - name: Compile firmware
      run: |
        cd openwrt
        make -j1 V=s

    - name: Upload firmware
      uses: actions/upload-artifact@main
      with:
        name: openwrt-firmware
        path: openwrt/bin
