name: Build OpenWrt openwrt-22.03 for x86_64

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  OPENWRT_BRANCH: openwrt-22.03
  CONFIG: config/openwrt-22.03-x86_64
  THREADS: $(nproc)
  CLEAN_DL: '1'

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout OpenWrt
      uses: actions/checkout@v3
      with:
        repository: openwrt/openwrt
        path: openwrt
        ref: $OPENWRT_BRANCH

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Show env
      run: |
        echo CONFIG is ${CONFIG}
        echo CONFIG is $CONFIG

    - name: Apply config
      run: |
        [ -e $CONFIG ] && cp  $CONFIG openwrt/.config
        cd openwrt
        ls -l .config

    - name: Make Download
      run: |
        cd openwrt
        make defconfig
        make download -j$THREADS

    - name: Compile
      run: |
        cd openwrt
        make -j$THREADS || make -j1 V=s

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-$OPENWRT_VERSION-x86_64
        path: openwrt/bin/targets/x86/64/*

