name: Build OpenWrt v22.03.5 for x86_64

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  OPENWRT_BRANCH: openwrt-22.03
  CONFIG: config/openwrt-22.03-x86_64
  THREADS: $(nproc)
  CLEAN_DL: '1'

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout OpenWrt
      uses: actions/checkout@v3
      with:
        repository: openwrt/openwrt
        path: openwrt
        ref: ${{env.OPENWRT_BRANCH}}

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Apply config
      run: |
        [ -e ${{env.CONFIG}} ] && cp  ${{env.CONFIG}} openwrt/.config
        cd openwrt

    - name: Make Download
      run: |
        cd openwrt
        make defconfig
        make download -j${{env.THREADS}}

    - name: Compile
      run: |
        cd openwrt
        make -j${{env.THREADS}} || make -j1 V=s

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-${{env.OPENWRT_VERSION}}-x86_64
        path: openwrt/bin/targets/x86_64/*

